<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\wmsearch\Exception\ApiException;
use Drupal\wmsearch\Entity\Document\DocumentInterface;
use Drupal\Core\TypedData\TranslatableInterface;

/**
 * Queue entities to be added/removed to/from the index.
 */
function wmsearch_queue(EntityInterface $e, $allTranslations = false)
{
    if (!$e instanceof DocumentInterface) {
        return;
    }

    $languages = [$e->language()];
    if (
        $allTranslations
        && $e instanceof TranslatableInterface
        && ($_languages = $e->getTranslationLanguages())
        && !empty($_languages)
    ) {
        $languages = $_languages;
    }

    foreach ($languages as $language) {
        \Drupal::service('queue')
            ->get('wmsearch.index')
            ->createItem(
                [
                    'type' => $e->getEntityTypeId(),
                    'language' => $language->getId(),
                    'id' => $e->id(),
                    'elasticId' => $e->getElasticId(),
                    'types' => $e->getElasticTypes(),
                ]
            );
    }
}

function wmsearch_entity_delete(EntityInterface $e)
{
    wmsearch_queue($e, true);
}

function wmsearch_entity_translation_delete(EntityInterface $e)
{
    wmsearch_queue($e);
}

function wmsearch_entity_update(EntityInterface $e)
{
    wmsearch_queue($e, true);
}

function wmsearch_entity_translation_update(EntityInterface $e)
{
    wmsearch_queue($e);
}

function wmsearch_entity_insert(EntityInterface $e)
{
    wmsearch_queue($e, true);
}

function wmsearch_entity_translation_insert(EntityInterface $e)
{
    wmsearch_queue($e);
}

function wmsearch_entity_id(EntityInterface $e)
{
    $id = $e->id();
    if (!$id) {
        throw new \RuntimeException(
            'Can not retrieve the elastic id for an entity without id'
        );
    }

    return wmsearch_id(
        $e->getEntityTypeId(),
        $e->language()->getId(),
        $id
    );
}

function wmsearch_id($type, $language, $id)
{
    return sprintf('%s:%s:%s', $type, $language, $id);
}

function wmsearch_rebuild()
{
    try {
        \Drupal::service('wmsearch.api')->createIndex();
    } catch (ApiException $e) {
        \Drupal::logger('wmsearch')->error($e->getMessage());
    }
}

