<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\wmsearch\Exception\ApiException;

/**
 * Queue entities to be added/removed to/from the index.
 */
function wmsearch_queue(EntityInterface $e)
{
    \Drupal::service('queue')
        ->get('wmsearch.index')
        ->createItem(['type' => $e->getEntityTypeId(), 'id' => $e->id()]);
}

function wmsearch_entity_delete(EntityInterface $e)
{
    wmsearch_queue($e);
}

function wmsearch_entity_update(EntityInterface $e)
{
    wmsearch_queue($e);
}

function wmsearch_entity_insert(EntityInterface $e)
{
    wmsearch_queue($e);
}

function wmsearch_rebuild()
{
    // Doesn't feel right, more appropriate place to do this.
    // ... what if elastic is down? no more drush cr?
    try {
        \Drupal::service('wmsearch.api')->createIndex();
    } catch (ApiException $e) {
        if (!$e->isIndexExists()) {
            throw $e;
        }
    }
}

